refac: it

diff --git a/.github/workflows/.release.yml b/.github/workflows/.release.yml
--- a/.github/workflows/.release.yml
+++ b/.github/workflows/.release.yml
@@ -1,5 +1,5 @@
-# release.yml
-name: Release & Publish
+
+name: Release & Publish Workflow
 
 on:
   workflow_dispatch:
@@ -14,9 +14,13 @@ on:
           - alpha
           - beta
           - rc
+  push:
+    tags:
+      - 'v*'  # Trigger on version tags
 
 jobs:
   release:
+    if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
     runs-on: ubuntu-latest
     permissions:
       contents: write  # Required for pushing code
@@ -36,7 +40,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0  # Important: fetch all history and tags
-          token: ${{ secrets.TOKEN_GITHUB }}  # Use the token here
+          # token: ${{ secrets.TOKEN_GITHUB }}
       
       - name: Install Node.js dependencies
         run: npm ci
@@ -46,11 +50,11 @@ jobs:
           git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
           git config --global user.name "${{ secrets.GIT_USER_NAME }}"
 
-      - name: Debug Git status before release
-        run: |
-          git status
-          git branch
-          git tag
+      # - name: Debug Git status before release
+      #   run: |
+      #     git status
+      #     git branch
+      #     git tag
           
       - name: Run release-it
         run: |
@@ -62,14 +66,98 @@ jobs:
         env:
           TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
           
-      - name: Debug Git status after release
-        run: |
-          git status
-          git branch
-          git tag
+      # - name: Debug Git status after release
+      #   run: |
+      #     git status
+      #     git branch
+      #     git tag
           
-      - name: Force push tags
-        run: git push --tags --force
+      # - name: Force push tags
+      #   run: git push --tags --force
+
+  publish:
+    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')  # Only run on version tag push
+    permissions:
+      id-token: write # Required for authentication using OIDC
+      contents: read  # Required for checking out code
+    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
+
+
+
+
+
+# # release.yml
+# name: Release & Publish
+
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       release-type:
+#         description: 'Specify release type: regular, alpha, beta, or rc'
+#         required: true
+#         default: 'regular'
+#         type: choice
+#         options:
+#           - regular
+#           - alpha
+#           - beta
+#           - rc
+
+# jobs:
+#   release:
+#     runs-on: ubuntu-latest
+#     permissions:
+#       contents: write  # Required for pushing code
+#       actions: write
+#     env:
+#       RELEASE_TYPE: ${{ github.event.inputs.release-type }}
+
+#     steps:
+#       - name: Validate branch
+#         run: |
+#           if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
+#             echo "Error: This workflow can only be run on the main branch."
+#             exit 1
+#           fi
+          
+#       - name: Checkout code
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 0  # Important: fetch all history and tags
+#           token: ${{ secrets.TOKEN_GITHUB }}  # Use the token here
+      
+#       - name: Install Node.js dependencies
+#         run: npm ci
+
+#       - name: Set Git user
+#         run: |
+#           git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
+#           git config --global user.name "${{ secrets.GIT_USER_NAME }}"
+
+#       - name: Debug Git status before release
+#         run: |
+#           git status
+#           git branch
+#           git tag
+          
+#       - name: Run release-it
+#         run: |
+#           if [ "$RELEASE_TYPE" == "regular" ]; then
+#             npx release-it --ci
+#           else
+#             npx release-it --ci --preRelease="$RELEASE_TYPE"
+#           fi
+#         env:
+#           TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
+          
+#       - name: Debug Git status after release
+#         run: |
+#           git status
+#           git branch
+#           git tag
+          
+#       - name: Force push tags
+#         run: git push --tags --force
 
 
 
