feat: one

diff --git a/.github/workflows/.release.yml b/.github/workflows/.release.yml
--- a/.github/workflows/.release.yml
+++ b/.github/workflows/.release.yml
@@ -1,63 +1,3 @@
-# name: Release & Publish
-
-# on:
-#   workflow_dispatch:
-#     inputs:
-#       release-type:
-#         description: 'Specify release type: regular, alpha, beta, or rc'
-#         required: true
-#         default: 'regular'
-#         type: choice
-#         options:
-#           - regular
-#           - alpha
-#           - beta
-#           - rc
-
-# jobs:
-#   release:
-#     runs-on: ubuntu-latest
-#     permissions:
-#       contents: write  # Required for pushing code
-#     env:
-#       RELEASE_TYPE: ${{ github.event.inputs.release-type }}
-
-#     steps:
-#       - name: Validate branch
-#         run: |
-#           if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
-#             echo "Error: This workflow can only be run on the main branch."
-#             exit 1
-#           fi
-#       - name: Checkout code
-#         uses: actions/checkout@v4
-      
-#       - name: Install Node.js dependencies
-#         run: npm ci
-
-#       - name: Set Git user
-#         run: |
-#           git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
-#           git config --global user.name "${{ secrets.GIT_USER_NAME }}"
-
-#       - name: Run release-it
-#         run: |
-#           if [ "$RELEASE_TYPE" == "regular" ]; then
-#             npx release-it
-#           else
-#             npx release-it --preRelease="$RELEASE_TYPE"
-#           fi
-#         env:
-#           TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
-
-#       - name: Verify Tag Creation
-#         run: git tag -l
-      
-#       - name: Verify Remote Tags
-#         run: git ls-remote --tags origin
-      
-        
-
 name: Release & Publish
 
 on:
@@ -75,12 +15,10 @@ on:
           - rc
 
 jobs:
-  # Job for manual version bump using release-it
   release:
-    if: github.event_name == 'workflow_dispatch'
-    permissions:
-      contents: write  # Required for creating releases
     runs-on: ubuntu-latest
+    permissions:
+      contents: write  # Required for pushing code
     env:
       RELEASE_TYPE: ${{ github.event.inputs.release-type }}
 
@@ -91,13 +29,12 @@ jobs:
             echo "Error: This workflow can only be run on the main branch."
             exit 1
           fi
-
-      - name: Checkout source code
+      - name: Checkout code
         uses: actions/checkout@v4
-
+      
       - name: Install Node.js dependencies
         run: npm ci
-    
+
       - name: Set Git user
         run: |
           git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
@@ -112,16 +49,79 @@ jobs:
           fi
         env:
           TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
-      
-      # - name: Wait for 30 seconds after release
-      #   run: sleep 30  # Waits for 30 seconds after release job completes
 
-  publish:
-    needs: release
-    # if: startsWith(github.ref, 'refs/tags/')
-    permissions:
-      id-token: write  # Required for authentication using OIDC
-    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
+      - name: Verify Tag Creation
+        run: git tag -l
+      
+      - name: Verify Remote Tags
+        run: git ls-remote --tags origin
+      
+        
+
+# name: Release & Publish
+
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       release-type:
+#         description: 'Specify release type: regular, alpha, beta, or rc'
+#         required: true
+#         default: 'regular'
+#         type: choice
+#         options:
+#           - regular
+#           - alpha
+#           - beta
+#           - rc
+
+# jobs:
+#   # Job for manual version bump using release-it
+#   release:
+#     if: github.event_name == 'workflow_dispatch'
+#     permissions:
+#       contents: write  # Required for creating releases
+#     runs-on: ubuntu-latest
+#     env:
+#       RELEASE_TYPE: ${{ github.event.inputs.release-type }}
+
+#     steps:
+#       - name: Validate branch
+#         run: |
+#           if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
+#             echo "Error: This workflow can only be run on the main branch."
+#             exit 1
+#           fi
+
+#       - name: Checkout source code
+#         uses: actions/checkout@v4
+
+#       - name: Install Node.js dependencies
+#         run: npm ci
+    
+#       - name: Set Git user
+#         run: |
+#           git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
+#           git config --global user.name "${{ secrets.GIT_USER_NAME }}"
+
+#       - name: Run release-it
+#         run: |
+#           if [ "$RELEASE_TYPE" == "regular" ]; then
+#             npx release-it
+#           else
+#             npx release-it --preRelease="$RELEASE_TYPE"
+#           fi
+#         env:
+#           TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
+      
+#       # - name: Wait for 30 seconds after release
+#       #   run: sleep 30  # Waits for 30 seconds after release job completes
+
+#   publish:
+#     needs: release
+#     # if: startsWith(github.ref, 'refs/tags/')
+#     permissions:
+#       id-token: write  # Required for authentication using OIDC
+#     uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
 
   # # This step runs if the condition fails
   #   else:
